alter table TESTWORK_PRODUCT add constraint FK_TESTWORK_PRODUCT_ON_ORDER foreign key (ORDER_ID) references TESTWORK_ORDER(ID);
create index IDX_TESTWORK_PRODUCT_ON_ORDER on TESTWORK_PRODUCT (ORDER_ID);
