alter table TESTWORK_ORDER add constraint FK_TESTWORK_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references TESTWORK_PRODUCT(ID);
create index IDX_TESTWORK_ORDER_ON_PRODUCT on TESTWORK_ORDER (PRODUCT_ID);
